# Generated by Django 5.2.4 on 2025-07-29 17:02

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, help_text='Short form (e.g., ASET, ALS, etc.)', max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='institutes/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this institute currently active?')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this institute featured on the homepage?')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.program')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('program', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='core.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='core.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='semesters',
            field=models.ManyToManyField(through='core.SubjectOffering', to='core.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'name')},
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('E', 'End Sem'), ('B', 'Back Paper')], default='E', max_length=1)),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, help_text='Auto-generated from filename if empty', max_length=300)),
                ('institute_name', models.CharField(blank=True, editable=False, max_length=200)),
                ('program_name', models.CharField(blank=True, editable=False, max_length=200)),
                ('semester_number', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('subject_code', models.CharField(blank=True, editable=False, max_length=20)),
                ('subject_name', models.CharField(blank=True, editable=False, max_length=200)),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='core.subjectoffering')),
            ],
            options={
                'ordering': ['-year', '-uploaded_at'],
                'indexes': [models.Index(fields=['year', 'paper_type'], name='core_exampa_year_95e7c6_idx'), models.Index(fields=['subject_code', 'year'], name='core_exampa_subject_c75efb_idx'), models.Index(fields=['institute_name', 'year'], name='core_exampa_institu_07d448_idx')],
            },
        ),
    ]
