# Generated by Django 5.2.4 on 2025-08-01 10:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='file',
            field=models.FileField(max_length=200, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='papers/'),
        ),
    ]
