# Generated by Django 5.2.4 on 2025-07-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this institute currently active?'),
        ),
        migrations.AddField(
            model_name='institute',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Is this institute featured on the homepage?'),
        ),
    ]
