# Generated by Django 5.2.4 on 2025-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_institute_is_active_institute_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
