# Generated by Django 5.2.4 on 2025-08-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exampaper_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='file',
            field=models.FileField(max_length=200, upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='institutes/'),
        ),
    ]
