# Generated by Django 5.2.4 on 2025-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institute_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampaper',
            options={'ordering': ['-year', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='exampaper',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='institute_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hide/show paper without deleting'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='program_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='semester_number',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='subject_code',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='subject_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated from filename if empty', max_length=300),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='paper_type',
            field=models.CharField(choices=[('E', 'End Sem'), ('M', 'Mid Sem'), ('B', 'Back Paper'), ('A', 'Assignment'), ('Q', 'Quiz'), ('P', 'Practical')], default='E', max_length=1),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['year', 'paper_type'], name='core_exampa_year_95e7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['subject_code', 'year'], name='core_exampa_subject_c75efb_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['institute_name', 'year'], name='core_exampa_institu_07d448_idx'),
        ),
    ]
