# Generated by Django 5.2.4 on 2025-08-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_issue_alter_exampaper_file_alter_institute_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
