# Generated by Django 5.2.4 on 2025-07-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_exampaper_options_exampaper_download_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='subject_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='core.subjectoffering'),
        ),
    ]
