# Generated by Django 5.2.4 on 2025-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exampaper_subject_offering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='paper_type',
            field=models.CharField(choices=[('E', 'End Sem'), ('B', 'Back Paper')], default='E', max_length=1),
        ),
    ]
