# Generated by Django 5.2.4 on 2025-07-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_exampaper_paper_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='download_count',
        ),
    ]
