# Generated by Django 5.2.4 on 2025-07-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_exampaper_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='is_active',
        ),
    ]
