# Generated by Django 5.2.4 on 2025-07-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_is_active_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='exampaper',
            name='file_size',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'name')},
        ),
    ]
